---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: objectstorage-composition
  labels:
    crossplane.io/xrd: xobjectstorages.defenseunicorns.com
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: xobjectstorages.defenseunicorns.com/v1alpha1
    kind: XObjectStorage
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: s3bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata: {}
        spec:
          forProvider:
            # public-read should enable public access for static website hosting
            # see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket
            acl: "public-read"
            websiteConfiguration:
              indexDocument: 
                suffix: "index.html"
          deletionPolicy: Delete
      patches:
        - fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.locationConstraint"